version: 2

updates:
  - directory: /packages/eslint-config
    package-ecosystem: npm
    reviewers:
      - vladyslavvolkov
    schedule:
      interval: daily

  - directory: /packages/stylelint-config
    package-ecosystem: npm
    reviewers:
      - vladyslavvolkov
    schedule:
      interval: daily

  - directory: /packages/webpack
    package-ecosystem: npm
    reviewers:
      - vladyslavvolkov
    schedule:
      interval: daily

  - directory: /packages/prettier-config
    package-ecosystem: npm
    reviewers:
      - vladyslavvolkov
    schedule:
      interval: daily
