enableGlobalCache: true
nodeLinker: node-modules
preferAggregateCacheInfo: true
nmSelfReferences: false
nmMode: hardlinks-local
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
yarnPath: .yarn/releases/yarn-3.1.0.cjs
logFilters:
  - level: discard
    code: YN0076
