enableGlobalCache: true

changesetBaseRefs:
  - refs/heads/latest
  - latest

preferDeferredVersions: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-3.5.0.cjs
