enableGlobalCache: true

logFilters:
  - code: YN0076
    level: discard

nmMode: hardlinks-local

nmSelfReferences: false

nodeLinker: node-modules

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-sources.cjs
