enableGlobalCache: true

logFilters:
  - code: YN0076
    level: discard

nmMode: hardlinks-local

nmSelfReferences: false

nodeLinker: node-modules

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.15.git.20220824.hash-a66e528.cjs

changesetBaseRefs:
  - latest
  - origin/latest
